server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.94.100.52/team_proj?serverTimezone=UTC
    username: root
    password: 0.123456a
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 1.94.100.52
    port: 6379
    password: 0.123456a
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
